language: go
go:
  - 1.1
  - 1.2
script:
 - sudo add-apt-repository -y ppa:rufustfirefly/ganglia
 - sudo apt-get update -qq
 - sudo apt-get install ganglia-monitor -qq
 - curl https://raw.github.com/daaku/go.travis/master/install | sh
